// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ktuwufktpgnrsvdlhhfy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt0dXd1Zmt0cGducnN2ZGxoaGZ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwODg3ODQsImV4cCI6MjA1OTY2NDc4NH0.3boN6yJX-Wt_kNtvmvbILOmMCAcZnFgEedmq6mBQX8c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);